server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: water-8080
  # 数据源配置信息
  datasource:
    url: jdbc:mysql://localhost:3306/water?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      # 最大连接数通常是CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      # 最大等待时间
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      # 空闲时间，单位是毫秒。连接空闲时间大于该值并且池中空闲连接大于minIdle则关闭该连接
      minEvictableIdleTimeMillis: 300000
      #测试连接是否可用的SQL语句，SELECT 1是MySQL的默认值
      validationQuery: SELECT 1
      # 应用向连接池获取连接的时候测试连接的有效性
      testWhileIdle: true
      testOnBorrow: false
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: false
      # 开启PreparedStatements Cache(提升写入、查询效率)，MySQL5.7以上建议true
      poolPreparedStatements: true
      # 打开Druid的监控统计功能
      # stat监控统计  log4j日志监控  wall防御sql注入
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  mvc:
    format:
      date: yyyy-MM-dd
  thymeleaf:
    cache: false
    prefix: classpath:/templates/water/
    suffix: .html
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resource,file:${location}

  # Springboot将从classpath中按如下优先级加载对应前端静态资源
  # classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resource
  # 除此之外还要加载E:/upLoad/picture/路径下的静态资源
  servlet:
    multipart:
      max-file-size: 2000000000000000

# 上传到服务器的路径
location: C:/Users/HUANGYAOHUI/Desktop/springboot/upLoad/picture/


# 配置MyBatis持久层框架
mybatis:
  # 执行实体类名称别名所在的包
  type-aliases-package: com.whut.water.entities
  configuration:
    # 开启驼峰命名，让数据库表的字段和Java实体类的属性完成映射
    map-underscore-to-camel-case: true
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置映射文件的位置
  mapper-locations: classpath:/mappers/*Mapper.xml
# 分页配置
pagehelper:
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数，默认为false，当该值为true，pageNum<=0默认查询第一页，
  # pageNum>pages时会查询最后一页，false时直接根据参数进行查询
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true
  params: count=countsql